name: ZJU-nCov-Hitcarder Sample

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            dingtalk_token: DINGTALK_TOKEN2
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
            dingtalk_token: DINGTALK_TOKEN3
          - username: ZJU_USERNAME4
            password: ZJU_PASSWORD4
            dingtalk_token: DINGTALK_TOKEN4
          - username: ZJU_USERNAME5
            password: ZJU_PASSWORD5
            dingtalk_token: DINGTALK_TOKEN5

    steps:
      - name: Checkout
        uses: actions/checkout@v2     
      - name: Working
        uses: sanlukuagnji/ZJU-nCov-Hitcarder@0.0.1 
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
