name: ZJU-nCov-Hitcarder Action

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            dingtalk_token: DINGTALK_TOKEN2
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
            dingtalk_token: DINGTALK_TOKEN3

    steps:     
      - name: Working
        uses: sanlukuangji/ZJU-nCov-Hitcarder@0.0.1 
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
